# -*- coding: utf-8 -*-
"""AI ASSIGNMENT 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i5vfb5sfHW7RK-Wd90QsG211_cnZEBos

ASSIGNMENT 2
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

"""Task 1 : Read the dataset and do data pre-processing"""

df=pd.read_csv('/content/drug200.csv')

df.describe(include='all')

df.isnull().sum()

df.info()

df['Drug'].unique()

X=df.iloc[:,0:5]
X.head()

Y=df['Drug']
Y.head()

xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.2,random_state=20)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

ytrain = le.fit_transform(ytrain)
ytest = le.transform(ytest)

ytrain.shape, ytest.shape

xtrain['Sex']=le.fit_transform(xtrain['Sex'])
xtrain['BP']=le.fit_transform(xtrain['BP'])
xtrain['Cholesterol']=le.fit_transform(xtrain['Cholesterol'])

xtrain.head(10)

xtest['Sex']=le.fit_transform(xtest['Sex'])
xtest['BP']=le.fit_transform(xtest['BP'])
xtest['Cholesterol']=le.transform(xtest['Cholesterol'])
xtest.head(10)

"""Task 2 : Build the ANN model with (input layer, min 3 hidden layers & output layer)"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model= Sequential()

model.add(Dense(5,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(5,activation='softmax'))

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.fit(xtrain,ytrain,epochs=10,batch_size=5,validation_data=(xtest,ytest))

"""Task 3 : Test the model with random data"""

ypred = model.predict([[49,1,0,2,8]])
print(ypred)

ypred = np.argmax(ypred)
output = ['DrugY', 'drugC', 'drugX', 'drugA', 'drugB']
output[ypred]