# -*- coding: utf-8 -*-
"""AI ASSIGNMENT 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AO2LpVVJyPiUhL1PIjui_QUaXUaqKY5J
"""

#Davidson Mahapatra 20BCD7005

#  1. Create a data frame having four random features and 4 observations

import pandas as pd
import numpy as np

k=np.random.randint(20,size=(4,4))

df1=pd.DataFrame(k)

df1

# 2.Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

df1.columns= ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']
df1

# 3.Find the descriptive statistics of the 'df' dataframe.

df1.describe()

# 4.Check for the null values in 'df' and find the data type of the columns.
df1.isnull()

#  5.Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.
df1.loc[:,'Random value 2' : 'Random value 3']

df1.iloc[:,[1,2]]